
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: private-eks
  region: eu-west-1
  version: "1.23"
availabilityZones:
- eu-west-1a
- eu-west-1b
managedNodeGroups:
- name: general
  privateNetworking: true
  instanceType: t3.medium
  desiredCapacity: 3
  minSize: 1 
  maxSize: 5